CREATE TABLE IF NOT EXISTS Notes (
    Name       TEXT NOT NULL PRIMARY KEY,
    Body       BLOB NOT NULL,
    Created    DATETIME DEFAULT CURRENT_TIMESTAMP,
    LastViewed DATETIME DEFAULT CURRENT_TIMESTAMP
);